language: node_js
node_js:
  - "14"
dist: bionic
sudo: required

services:
  - xvfb

branches:
  only:
  - ng-app

before_script:
  - npm install -g @angular/cli@10
  - npm install -g codecov

script:
  - ng lint
  - ng build --prod --base-href /
  - xvfb-run npm run coverage
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/github-home-app
  target-branch: master
  on:
    branch: ng-app
